#pragma once
#include <vdl/Topology.hpp>

#include <d3dcommon.h>
#include <assert.h>

inline constexpr D3D_PRIMITIVE_TOPOLOGY Cast(vdl::TopologyType _Topology)
{
  switch (_Topology)
  {
  case vdl::TopologyType::ePointList:
    return D3D_PRIMITIVE_TOPOLOGY_POINTLIST;
  case vdl::TopologyType::eLineList:
    return D3D_PRIMITIVE_TOPOLOGY_LINELIST;
  case vdl::TopologyType::eLineStrip:
    return D3D_PRIMITIVE_TOPOLOGY_LINESTRIP;
  case vdl::TopologyType::eTriangleList:
    return D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST;
  case vdl::TopologyType::eTriangleStrip:
    return D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP;
  case vdl::TopologyType::ePatchList1ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList2ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList3ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList4ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList5ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList6ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList7ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList8ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList9ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList10ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList11ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList12ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList13ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList14ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList15ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList16ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList17ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_17_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList18ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_18_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList19ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_19_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList20ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_20_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList21ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_21_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList22ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_22_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList23ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_23_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList24ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_24_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList25ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_25_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList26ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_26_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList27ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_27_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList28ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_28_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList29ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_29_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList30ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_30_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList31ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_31_CONTROL_POINT_PATCHLIST;
  case vdl::TopologyType::ePatchList32ControlPoint:
    return D3D_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST;
  default: assert(false);
  }

  return D3D_PRIMITIVE_TOPOLOGY_UNDEFINED;
}
